# Generated by Django 4.2.13 on 2024-06-27 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TOP_PRIORITIES', 'Top Priorities'), ('SCORE_CHANGES', 'Score Changes'), ('BUDGETING_AND_SPENDING', 'Budgeting & Spending'), ('PROFILE_UPDATES', 'Profile Updates'), ('REPORTS_AND_RECAPS', 'Reports & Recaps')], error_messages={'unique': 'Notification Type already exists'}, max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('INSTANTLY', 'Instantly'), ('PERIODICALLY', 'Periodically'), ('RARELY', 'Rarely')], default='INSTANTLY', max_length=13)),
                ('email', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('notification_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='notification_mgmt.notificationtype')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
